#include <sgtdv_msgs/Point2D.h>
#include <sgtdv_msgs/Point2DArr.h>
#include <sgtdv_msgs/Point2DStamped.h>
#include <sgtdv_msgs/Point2DStampedArr.h>
#include <sgtdv_msgs/Cone.h>
#include <sgtdv_msgs/ConeArr.h>
#include <sgtdv_msgs/ConeStamped.h>
#include <sgtdv_msgs/ConeStampedArr.h>
#include <sgtdv_msgs/ConeWithCovStamped.h>
#include <sgtdv_msgs/ConeWithCovStampedArr.h>
#include <sgtdv_msgs/ColoredConeArr.h>
#include <sgtdv_msgs/CarPose.h>
#include <sgtdv_msgs/CarVel.h>
#include <sgtdv_msgs/Control.h>
#include <sgtdv_msgs/DebugState.h>
#include <sgtdv_msgs/PathPlanningMsg.h>
#include <sgtdv_msgs/PathTrackingMsg.h>
#include <sgtdv_msgs/SLAMMsg.h>
int main() { return 0; }